### ISSUE TITLE
Update About Page

### ISSUE THREAD

**Issue by pwalters04** [avischiffmann/Coronavirus-Dashboard#10]
I noticed you have additional contributors that assist on this project. It would be nice to see her name mentioned as well.

**Comment by avischiffmann** [comment]
Hi I work closely with her, she so far hasn’t wanted her name on there but I will ask her again

**Comment by pwalters04** [comment]
Thank you, for the support!  It's important to show women and men can work together to create something for the world. Keep doing your thing. I know you will become something big in the world at the rate you are going!

**Comment by jensechu** [comment]
Thanks @pwalters04. 😄 Happy International Women's day!

**Comment by pwalters04** [comment]
You're Welcome!! Happy International Women's Day!!! @jensechu
