### ISSUE TITLE
Set up data section using tables 

### ISSUE THREAD

**Issue by alexweininger** [avischiffmann/Coronavirus-Dashboard#15]
https://getbootstrap.com/docs/4.0/content/tables/

![image](https://user-images.githubusercontent.com/12476526/76153593-e90a4200-6082-11ea-8279-62a7fe7e7aeb.png)

you could use tables from bootstrap to easily make the data on the data page a lot more useful and presentable. This would automatically add sorting, coloring, filtering, etc to the data page.

I know that you technically are using tables in the html. But if you use the bootstrap tables it would make the data more readable.

**Comment by alexweininger** [comment]
![image](https://user-images.githubusercontent.com/12476526/76153721-aba6b400-6084-11ea-83c7-558a4b29a792.png)
I got something kind of working here as an example.

**Comment by jensechu** [comment]
We haven't touched this quite yet because the goal was to move over to using DataTables! If you want to have a go at that and PR it that'd be neat.

**Comment by alexweininger** [comment]
DataTables from what framework? Are you referring to this https://datatables.net/ ?

I was playing around with the bootstrap tables and they are looking pretty nice:

![image](https://user-images.githubusercontent.com/12476526/76153859-5fa93e80-6087-11ea-97cd-5fabba5e89a7.png)

I absolutely love this project!

**Comment by jensechu** [comment]
This looks really nice! How does it look on mobile? A huge portion of the traffic is on mobile. And yep that is the one! It allows sorting which is great.

**Comment by alexweininger** [comment]
Using this it makes the table horizontal scroll able on mobile: 
https://getbootstrap.com/docs/4.0/content/tables/#always-responsive

**Comment by jensechu** [comment]
Ah I think maybe for desktop it'd be great to use your table! Then we could use something more mobile friendly in the mobile breakpoint. It looks good.

**Comment by alexweininger** [comment]
Ok - how would you like me/us to implement that?

Also what do you have in mind for a mobile friendly table? It's a little tricky because of all the data we are trying to convey on one page, especially on mobile :)

**Comment by jensechu** [comment]
Whatever you did above looks great to me. We can add something in `styles.css` that hides/shows the table in desktop/mobile. So we would render both on the page and let the `.css` handle the display depending on viewport size.

If you want to PR however far you get maybe I could provide feedback from there. 😄 

For mobile I agree its trickier. Maybe an inline list that's display: flex then justify-content: space-between. If you just PR at least desktop I think we could move forward from there and play around with some ideas. 

Really appreciate the help! 💪

**Comment by avischiffmann** [comment]
I had something earlier that did a media query for mobile and switched to the current design from a table when you were on a phone for example. Desktop for datatables makes the most sense tbh, horizontal tables are terrible on a phone
