### ISSUE TITLE
Inconsistent data for Czechia and the Czech republic

### ISSUE THREAD

**Issue by FrantisekHrdina** [avischiffmann/Coronavirus-Dashboard#39]
Czechia and the Czech Republic are two different names for one country. In Global, there is the Czech Republic with 116 confirmed cases and in Europe, there is just Czechia with 120 confirmed cases.

**Comment by avischiffmann** [comment]
We are working on syncing

**Comment by FrantisekHrdina** [comment]
It seems to be okay now. Thanks.

**Comment by jensechu** [comment]
This was fixed so I'll close! Thanks for reporting it.
