### ISSUE TITLE
Double Country Panama vs Panamá

### ISSUE THREAD

**Issue by frequencx** [avischiffmann/Coronavirus-Dashboard#58]
The Global view shows **Panama** with 69 cases - which seems to be correct.
The Latin America view shows **Panamá** with only 14 cases.

Thanks for the great site!

**Comment by chetanddesai** [comment]
<img width="512" alt="Screen Shot 2020-03-19 at 7 59 59 AM" src="https://user-images.githubusercontent.com/1682406/77081301-a5cf9d80-69b7-11ea-9adf-c2079b8ece31.png">

This ticket looks resolved last I checked - it matches the Global view now

**Comment by frequencx** [comment]
Super - thanks for checking!
