### ISSUE TITLE
Installing and Running locally with Firebase

### ISSUE THREAD

**Issue by ojsimon** [avischiffmann/Coronavirus-Dashboard#69]
Hi, 

Great work. I have been trying to clone and run locally. 

I tried NPM Install and Yarn Install. 

I then tried NPM build but am getting errors. 

Can you give any suggestions for how to build locally or on Firebase?

Thanks

**Comment by trycrmr** [comment]
I was able to build locally, but I did receive an error about one of the .csv's the first time. But when I ran `npm run server` a second time I didn't see the error. 

Would you mind sharing some details about the errors you're seeing? Node 13.9.0 on Ubuntu 18.04.4 is my environment.

**Comment by ojsimon** [comment]
@trycrmr yes that actually worked locally. When I try to deploy onto firebase I just `[get this error](https://copo-a0b73.firebaseapp.com/)`. Any idea how I solve that?

**Comment by trycrmr** [comment]
Ah, nope, just running locally at the moment.

**Comment by ojsimon** [comment]
Can anyone else help?

**Comment by jensechu** [comment]
Sorry. I haven't used Firebase before so I can't help you there.

**Comment by jensechu** [comment]
Since your core issue is Firebase and not our app I am going to close this but I hope you can figure it out! 👍

**Comment by ojsimon** [comment]
Thanks @jensechu  - How about Netlify or another similar?
