### ISSUE TITLE
statusCode500

### ISSUE THREAD

**Issue by alanleung2017** [avischiffmann/Coronavirus-Dashboard#83]
it's response 500 internal server error now

**Comment by jensechu** [comment]
Resolved. Thanks for posting! 👍

**Comment by alanleung2017** [comment]
you are welcome. What is the backend language of this project?

**Comment by jensechu** [comment]
javascript 😄

**Comment by alanleung2017** [comment]
> javascript 😄
it's the best language in the world，lol
